### ISSUE TITLE
Hilt Fragments should not be retained

### ISSUE THREAD

**Issue by gaborauth** [gaborauth/toolsboox-android#25]
**Describe the bug**

`onAttach called multiple times with different Context! Hilt Fragments should not be retained.`

**The stacktrace**
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.toolsboox/com.toolsboox.ui.main.MainActivity}: java.lang.IllegalStateException: onAttach called multiple times with different Context! Hilt Fragments should not be retained.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3473)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3625)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5488)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5394)
```

**Device details:**
 - Device: -
 - OS: -
 - Version 1.3.0.

**Additional context**
https://console.firebase.google.com/u/0/project/toolboox-7ac1f/crashlytics/app/android:com.toolsboox/issues/05321dcbb17f94ddf88cf562e5d19553

**Comment by gaborauth** [comment]
Fixed.
