### ISSUE TITLE
Crash when entering Kanban Board

### ISSUE THREAD

**Issue by wojta** [gaborauth/toolsboox-android#31]
**Describe the bug**
App crashes when entering the Kanban Board from the main screen.

**The stacktrace**
```
 2022-10-22 17:54:38.223 22917-23057/com.toolsboox.debug E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.toolsboox.debug, PID: 22917
    kotlin.UninitializedPropertyAccessException: lateinit property previewCanvas has not been initialized
        at com.toolsboox.plugin.kanban.ui.KanbanMainFragment.placeCardItems(KanbanMainFragment.kt:385)
        at com.toolsboox.plugin.kanban.ui.KanbanMainFragment.renderLoad(KanbanMainFragment.kt:351)
        at com.toolsboox.plugin.kanban.ui.KanbanMainPresenter$loadLocal$1$4.invokeSuspend(KanbanMainPresenter.kt:58)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7547)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c0d0c06, Dispatchers.IO]
```

**Device details:**
 - Device: Nova3
 - OS: 2022-04-27_13-09_3.2.2_22c834b
 - Version local developer build - commit d2d49b54c0adea8a235a283f08ecd8f28e26c5eb

**Additional context**
It clearly changes orientation in the process of loading.

**Probable cause**
I think that you're launching coroutines that are not lifecycle-aware with the GlobalScope. Probably it ends up running on recreated fragment that doesn't get the property initialized.

https://github.com/gaborauth/toolsboox-android/blob/8e1904c39cd301bb91e7fc97b66eeddf5244ba9c/app/src/main/java/com/toolsboox/plugin/kanban/ui/KanbanMainPresenter.kt#L33

Not sure, but I don't have time to investigate that to the detail. I would recommend using standard ViewModel components and viewModelScope and passing changes to the UI using Flows or LiveData. It solves lot of pain points like that.
https://developer.android.com/topic/libraries/architecture/coroutines#lifecycle-aware

**Comment by gaborauth** [comment]
Thank you for your feedback!

I'm aware about the issue, but I'm currently working on the 'Calendar' plugin, and the whole 'Kanban planner' needs a whole rewrite and redesign. At the moment, it is very experimental and some part of it obsoleted. :)

![image](https://user-images.githubusercontent.com/16724720/197378944-37ca0559-f82c-46bf-b244-a63ba365381c.png)

**Comment by gaborauth** [comment]
Fixed.
