### ISSUE TITLE
NullPointerException in PageFragment.onViewCreated

### ISSUE THREAD

**Issue by gaborauth** [gaborauth/toolsboox-android#37]
**Describe the bug**
Create a new note in the Teamdrawer plugin.

**The stacktrace**
```
    java.lang.NullPointerException
        at com.toolsboox.plugin.teamdrawer.ui.PageFragment.onViewCreated(PageFragment.kt:141)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
```

**Device details:**
 - Device: Note Air
 - OS: 3.2.4
 - Version: 1.4.2+

**Comment by gaborauth** [comment]
Fixed in [3b44fbce543414a7e7fdc785929f9483a364c04e](https://github.com/gaborauth/toolsboox-android/commit/3b44fbce543414a7e7fdc785929f9483a364c04e)
